// Code generated by protoc-gen-ext. DO NOT EDIT.
// source: github.com/solo-io/gloo/projects/gloo/api/v1/options/static_eds/static_eds.proto

package static_eds

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"strings"

	"github.com/golang/protobuf/proto"
	equality "github.com/solo-io/protoc-gen-ext/pkg/equality"
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print
	_ = binary.LittleEndian
	_ = bytes.Compare
	_ = strings.Compare
	_ = equality.Equalizer(nil)
	_ = proto.Message(nil)
)

// Equal function
func (m *UpstreamSpec) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*UpstreamSpec)
	if !ok {
		that2, ok := that.(UpstreamSpec)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if len(m.GetLocalityEndpoints()) != len(target.GetLocalityEndpoints()) {
		return false
	}
	for idx, v := range m.GetLocalityEndpoints() {

		if h, ok := interface{}(v).(equality.Equalizer); ok {
			if !h.Equal(target.GetLocalityEndpoints()[idx]) {
				return false
			}
		} else {
			if !proto.Equal(v, target.GetLocalityEndpoints()[idx]) {
				return false
			}
		}

	}

	if m.GetUseTls() != target.GetUseTls() {
		return false
	}

	if h, ok := interface{}(m.GetServiceSpec()).(equality.Equalizer); ok {
		if !h.Equal(target.GetServiceSpec()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetServiceSpec(), target.GetServiceSpec()) {
			return false
		}
	}

	if h, ok := interface{}(m.GetAutoSniRewrite()).(equality.Equalizer); ok {
		if !h.Equal(target.GetAutoSniRewrite()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetAutoSniRewrite(), target.GetAutoSniRewrite()) {
			return false
		}
	}

	return true
}

// Equal function
func (m *LocalityLbEndpoints) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*LocalityLbEndpoints)
	if !ok {
		that2, ok := that.(LocalityLbEndpoints)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if h, ok := interface{}(m.GetLocality()).(equality.Equalizer); ok {
		if !h.Equal(target.GetLocality()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetLocality(), target.GetLocality()) {
			return false
		}
	}

	if len(m.GetLbEndpoints()) != len(target.GetLbEndpoints()) {
		return false
	}
	for idx, v := range m.GetLbEndpoints() {

		if h, ok := interface{}(v).(equality.Equalizer); ok {
			if !h.Equal(target.GetLbEndpoints()[idx]) {
				return false
			}
		} else {
			if !proto.Equal(v, target.GetLbEndpoints()[idx]) {
				return false
			}
		}

	}

	if h, ok := interface{}(m.GetLoadBalancingWeight()).(equality.Equalizer); ok {
		if !h.Equal(target.GetLoadBalancingWeight()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetLoadBalancingWeight(), target.GetLoadBalancingWeight()) {
			return false
		}
	}

	return true
}

// Equal function
func (m *LbEndpoint) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*LbEndpoint)
	if !ok {
		that2, ok := that.(LbEndpoint)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if strings.Compare(m.GetAddr(), target.GetAddr()) != 0 {
		return false
	}

	if m.GetPort() != target.GetPort() {
		return false
	}

	if strings.Compare(m.GetSniAddr(), target.GetSniAddr()) != 0 {
		return false
	}

	if h, ok := interface{}(m.GetHealthCheckConfig()).(equality.Equalizer); ok {
		if !h.Equal(target.GetHealthCheckConfig()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetHealthCheckConfig(), target.GetHealthCheckConfig()) {
			return false
		}
	}

	return true
}

// Equal function
func (m *Locality) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*Locality)
	if !ok {
		that2, ok := that.(Locality)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if strings.Compare(m.GetRegion(), target.GetRegion()) != 0 {
		return false
	}

	if strings.Compare(m.GetZone(), target.GetZone()) != 0 {
		return false
	}

	if strings.Compare(m.GetSubZone(), target.GetSubZone()) != 0 {
		return false
	}

	return true
}

// Equal function
func (m *LbEndpoint_HealthCheckConfig) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*LbEndpoint_HealthCheckConfig)
	if !ok {
		that2, ok := that.(LbEndpoint_HealthCheckConfig)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if strings.Compare(m.GetPath(), target.GetPath()) != 0 {
		return false
	}

	return true
}
